name: DevSecOps Pipeline

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node dependencies
        working-directory: api
        run: npm install

      - name: Run npm audit
        working-directory: api
        run: npm audit --audit-level=high
        continue-on-error: true